import type { Trade } from './types';

export const PLUMBING_TRADE: Trade = {
    id: 'plumbing',
    name: 'Plumbing',
    description: 'Industrial and domestic water systems, sanitation, and fluid dynamics infrastructure development.',
    icon: '🔧',
    moduleCount: 12,
    gradientFrom: '#1e3a5f',
    gradientTo: '#2d6a9f',
    subjects: [
        {
            id: 'pl-trade-theory',
            name: 'Trade Theory',
            topics: [
                { id: 'pl-tt-l1-1', name: 'Introduction to Plumbing', type: 'THEORY', hours: 4, level: 1 },
                { id: 'pl-tt-l1-2', name: 'Tools & Equipment', type: 'PRACTICAL', hours: 3, level: 1 },
                { id: 'pl-tt-l1-3', name: 'Plumbing Materials', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-tt-l1-4', name: 'Cold Water Supply Systems', type: 'THEORY', hours: 4, level: 1 },
                { id: 'pl-tt-l1-5', name: 'Joining Methods', type: 'PRACTICAL', hours: 3, level: 1 },
                { id: 'pl-tt-l1-6', name: 'Sanitation Basics', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-tt-l1-7', name: 'Introduction to Drainage', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-tt-l2-1', name: 'Advanced Water Supply', type: 'PRACTICAL', hours: 5, level: 2 },
                { id: 'pl-tt-l2-2', name: 'Advanced Pipe Work', type: 'PRACTICAL', hours: 5, level: 2 },
                { id: 'pl-tt-l2-3', name: 'Sanitation Systems (Advanced)', type: 'PRACTICAL', hours: 4, level: 2 },
                { id: 'pl-tt-l2-4', name: 'Drainage Systems (Advanced)', type: 'THEORY', hours: 4, level: 2 },
                { id: 'pl-tt-l2-5', name: 'Roof Drainage', type: 'THEORY', hours: 3, level: 2 },
                { id: 'pl-tt-l2-6', name: 'Pumps & Pumping Systems', type: 'PRACTICAL', hours: 5, level: 2 },
                { id: 'pl-tt-l2-7', name: 'Gas Installations (Introduction)', type: 'THEORY', hours: 4, level: 2 },
                { id: 'pl-tt-l2-8', name: 'Water Treatment (Basic)', type: 'THEORY', hours: 3, level: 2 },
                { id: 'pl-tt-l3-1', name: 'Advanced Hot Water Systems', type: 'PRACTICAL', hours: 6, level: 3 },
                { id: 'pl-tt-l3-2', name: 'Advanced Gas Installations', type: 'PRACTICAL', hours: 6, level: 3 },
                { id: 'pl-tt-l3-3', name: 'Fire Protection Systems', type: 'THEORY', hours: 5, level: 3 },
                { id: 'pl-tt-l3-4', name: 'Industrial Plumbing', type: 'PRACTICAL', hours: 6, level: 3 },
                { id: 'pl-tt-l3-5', name: 'Swimming Pool Plumbing', type: 'PRACTICAL', hours: 4, level: 3 },
                { id: 'pl-tt-l3-6', name: 'Irrigation Systems', type: 'PRACTICAL', hours: 4, level: 3 },
                { id: 'pl-tt-l3-7', name: 'Project Planning & Estimation', type: 'THEORY', hours: 5, level: 3 },
                { id: 'pl-tt-l3-8', name: 'Maintenance & Fault Finding', type: 'PRACTICAL', hours: 5, level: 3 },
            ],
        },
        {
            id: 'pl-mathematics',
            name: 'Mathematics',
            topics: [
                { id: 'pl-m-l1-1', name: 'Basic Arithmetic', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-m-l1-2', name: 'Fractions & Decimals', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-m-l1-3', name: 'Measurement & Units', type: 'THEORY', hours: 2, level: 1 },
                { id: 'pl-m-l1-4', name: 'Perimeter & Area', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-m-l1-5', name: 'Basic Geometry', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-m-l1-6', name: 'Introduction to Algebra', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-m-l2-1', name: 'Algebraic Equations', type: 'THEORY', hours: 4, level: 2 },
                { id: 'pl-m-l2-2', name: 'Ratios & Proportions', type: 'THEORY', hours: 3, level: 2 },
                { id: 'pl-m-l2-3', name: 'Areas & Volumes', type: 'THEORY', hours: 4, level: 2 },
                { id: 'pl-m-l2-4', name: 'Pythagoras Theorem', type: 'THEORY', hours: 3, level: 2 },
                { id: 'pl-m-l2-5', name: 'Percentages', type: 'THEORY', hours: 2, level: 2 },
                { id: 'pl-m-l2-6', name: 'Linear Equations', type: 'THEORY', hours: 3, level: 2 },
                { id: 'pl-m-l3-1', name: 'Trigonometry', type: 'THEORY', hours: 5, level: 3 },
                { id: 'pl-m-l3-2', name: 'Logarithms', type: 'THEORY', hours: 3, level: 3 },
                { id: 'pl-m-l3-3', name: 'Statistics Basics', type: 'THEORY', hours: 3, level: 3 },
                { id: 'pl-m-l3-4', name: 'Graphs & Functions', type: 'THEORY', hours: 4, level: 3 },
                { id: 'pl-m-l3-5', name: 'Advanced Mensuration', type: 'THEORY', hours: 4, level: 3 },
                { id: 'pl-m-l3-6', name: 'Vectors', type: 'THEORY', hours: 3, level: 3 },
            ],
        },
        {
            id: 'pl-eng-science',
            name: 'Engineering Science',
            topics: [
                { id: 'pl-es-l1-1', name: 'Forces & Pressure', type: 'THEORY', hours: 4, level: 1 },
                { id: 'pl-es-l1-2', name: 'Properties of Water', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-es-l1-3', name: 'Basic Electricity', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-es-l1-4', name: 'Matter & Materials', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-es-l1-5', name: 'Levers & Machines', type: 'THEORY', hours: 3, level: 1 },
                { id: 'pl-es-l2-1', name: 'Fluid Mechanics', type: 'THEORY', hours: 5, level: 2 },
                { id: 'pl-es-l2-2', name: "Bernoulli's Principle", type: 'THEORY', hours: 4, level: 2 },
                { id: 'pl-es-l2-3', name: 'Pumps & Hydraulics', type: 'PRACTICAL', hours: 5, level: 2 },
                { id: 'pl-es-l2-4', name: 'Thermal Expansion', type: 'THEORY', hours: 3, level: 2 },
                { id: 'pl-es-l2-5', name: 'Work, Power & Energy', type: 'THEORY', hours: 4, level: 2 },
                { id: 'pl-es-l3-1', name: 'Thermodynamics', type: 'THEORY', hours: 5, level: 3 },
                { id: 'pl-es-l3-2', name: 'Heat Transfer', type: 'THEORY', hours: 4, level: 3 },
                { id: 'pl-es-l3-3', name: 'Advanced Mechanics', type: 'THEORY', hours: 5, level: 3 },
                { id: 'pl-es-l3-4', name: 'Momentum & Energy', type: 'THEORY', hours: 4, level: 3 },
                { id: 'pl-es-l3-5', name: 'Wave Motion', type: 'THEORY', hours: 3, level: 3 },
            ],
        },
        {
            id: 'pl-eng-drawing',
            name: 'Engineering Drawing',
            topics: [
                { id: 'pl-ed-l1-1', name: 'Drawing Instruments', type: 'PRACTICAL', hours: 2, level: 1 },
                { id: 'pl-ed-l1-2', name: 'Lines and Lettering', type: 'PRACTICAL', hours: 2, level: 1 },
                { id: 'pl-ed-l1-3', name: 'Geometric Construction', type: 'PRACTICAL', hours: 3, level: 1 },
                { id: 'pl-ed-l1-4', name: 'Introduction to Symbols', type: 'THEORY', hours: 2, level: 1 },
                { id: 'pl-ed-l1-5', name: 'Basic Sketching', type: 'PRACTICAL', hours: 2, level: 1 },
                { id: 'pl-ed-l2-1', name: 'Orthographic Projection', type: 'PRACTICAL', hours: 4, level: 2 },
                { id: 'pl-ed-l2-2', name: 'Sectional Views', type: 'PRACTICAL', hours: 3, level: 2 },
                { id: 'pl-ed-l2-3', name: 'Dimensioning', type: 'PRACTICAL', hours: 3, level: 2 },
                { id: 'pl-ed-l2-4', name: 'Plumbing Symbols', type: 'THEORY', hours: 2, level: 2 },
                { id: 'pl-ed-l2-5', name: 'Detail Drawings', type: 'PRACTICAL', hours: 4, level: 2 },
                { id: 'pl-ed-l3-1', name: 'Isometric Drawing', type: 'PRACTICAL', hours: 4, level: 3 },
                { id: 'pl-ed-l3-2', name: 'Assembly Drawings', type: 'PRACTICAL', hours: 4, level: 3 },
                { id: 'pl-ed-l3-3', name: 'Pipe Layout Drawings', type: 'PRACTICAL', hours: 4, level: 3 },
                { id: 'pl-ed-l3-4', name: 'Site Plans', type: 'PRACTICAL', hours: 3, level: 3 },
                { id: 'pl-ed-l3-5', name: 'Working Drawings', type: 'PRACTICAL', hours: 4, level: 3 },
            ],
        },
    ],
};
