import {
  FiBriefcase,
  FiCode,
  FiMessageSquare,
  FiBarChart2,
  FiShield,
  FiFeather,
  FiUsers,
  FiTrendingUp
} from "react-icons/fi";
import type { Course } from "@/components/home/CourseCard";
import type { Category } from "@/components/home/CategoryCard";

export const categories: Category[] = [
  {
    id: "1",
    name: "Leadership",
    icon: FiBriefcase,
    courseCount: 45,
    color: "#024F9D",
  },
  {
    id: "2",
    name: "IT & Software",
    icon: FiCode,
    courseCount: 120,
    color: "#16A34A",
  },
  {
    id: "3",
    name: "Communication",
    icon: FiMessageSquare,
    courseCount: 38,
    color: "#DC2626",
  },
  {
    id: "4",
    name: "Data Analytics",
    icon: FiBarChart2,
    courseCount: 67,
    color: "#7C3AED",
  },
  {
    id: "5",
    name: "Cybersecurity",
    icon: FiShield,
    courseCount: 34,
    color: "#0891B2",
  },
  {
    id: "6",
    name: "Design",
    icon: FiFeather,
    courseCount: 52,
    color: "#EA580C",
  },
  {
    id: "7",
    name: "HR & Management",
    icon: FiUsers,
    courseCount: 41,
    color: "#BE185D",
  },
  {
    id: "8",
    name: "Sales & Marketing",
    icon: FiTrendingUp,
    courseCount: 58,
    color: "#4F46E5",
  },
];

export const featuredCourses: Course[] = [
  {
    id: "1",
    title: "Leadership Excellence: Managing Teams in the Modern Workplace",
    instructor: "Dr. Sarah Johnson",
    thumbnail: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=225&fit=crop",
    rating: 4.9,
    reviewCount: 2340,
    duration: "12 hours",
    lessons: 48,
    enrolledCount: 15420,
    category: "Leadership",
    level: "Advanced",
    isFeatured: true,
  },
  {
    id: "2",
    title: "Complete Python Programming: From Zero to Professional",
    instructor: "Michael Chen",
    thumbnail: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?w=400&h=225&fit=crop",
    rating: 4.8,
    reviewCount: 5621,
    duration: "40 hours",
    lessons: 156,
    enrolledCount: 42150,
    category: "IT & Software",
    level: "Beginner",
    isFeatured: true,
  },
  {
    id: "3",
    title: "Effective Business Communication & Presentation Skills",
    instructor: "Emily Rodriguez",
    thumbnail: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=225&fit=crop",
    rating: 4.7,
    reviewCount: 1823,
    duration: "8 hours",
    lessons: 32,
    enrolledCount: 8930,
    category: "Communication",
    level: "Intermediate",
    isFeatured: true,
  },
  {
    id: "4",
    title: "Data Analytics with Excel, SQL & Tableau",
    instructor: "David Park",
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=225&fit=crop",
    rating: 4.8,
    reviewCount: 3456,
    duration: "25 hours",
    lessons: 98,
    enrolledCount: 21340,
    category: "Data Analytics",
    level: "Beginner",
    isFeatured: true,
  },
];

export const popularCourses: Course[] = [
  {
    id: "5",
    title: "Project Management Professional (PMP) Certification Prep",
    instructor: "James Wilson",
    thumbnail: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=225&fit=crop",
    rating: 4.9,
    reviewCount: 4521,
    duration: "35 hours",
    lessons: 124,
    enrolledCount: 28450,
    category: "Leadership",
    level: "Advanced",
  },
  {
    id: "6",
    title: "AWS Solutions Architect Associate Certification",
    instructor: "Lisa Thompson",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=225&fit=crop",
    rating: 4.8,
    reviewCount: 2987,
    duration: "28 hours",
    lessons: 112,
    enrolledCount: 19870,
    category: "IT & Software",
    level: "Intermediate",
  },
  {
    id: "7",
    title: "Negotiation Mastery: Art of Closing Deals",
    instructor: "Robert Martinez",
    thumbnail: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=400&h=225&fit=crop",
    rating: 4.7,
    reviewCount: 1654,
    duration: "10 hours",
    lessons: 42,
    enrolledCount: 7650,
    category: "Sales & Marketing",
    level: "Intermediate",
  },
  {
    id: "8",
    title: "Cybersecurity Fundamentals: Protect Your Organization",
    instructor: "Amanda Foster",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=225&fit=crop",
    rating: 4.8,
    reviewCount: 2134,
    duration: "20 hours",
    lessons: 76,
    enrolledCount: 12340,
    category: "Cybersecurity",
    level: "Beginner",
  },
  {
    id: "9",
    title: "UX/UI Design Masterclass: Create Stunning Interfaces",
    instructor: "Jessica Lee",
    thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=225&fit=crop",
    rating: 4.9,
    reviewCount: 3210,
    duration: "32 hours",
    lessons: 128,
    enrolledCount: 16780,
    category: "Design",
    level: "Beginner",
  },
  {
    id: "10",
    title: "Advanced Excel: Power Query, Pivot Tables & Macros",
    instructor: "Kevin Brown",
    thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=225&fit=crop",
    rating: 4.7,
    reviewCount: 4123,
    duration: "18 hours",
    lessons: 72,
    enrolledCount: 24560,
    category: "Data Analytics",
    level: "Intermediate",
  },
  {
    id: "11",
    title: "HR Management: Recruitment, Training & Development",
    instructor: "Nicole Adams",
    thumbnail: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=400&h=225&fit=crop",
    rating: 4.6,
    reviewCount: 1432,
    duration: "15 hours",
    lessons: 58,
    enrolledCount: 6890,
    category: "HR & Management",
    level: "Intermediate",
  },
  {
    id: "12",
    title: "Digital Marketing Complete Course: SEO, Ads & Social Media",
    instructor: "Chris Taylor",
    thumbnail: "https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=400&h=225&fit=crop",
    rating: 4.8,
    reviewCount: 5432,
    duration: "38 hours",
    lessons: 142,
    enrolledCount: 31240,
    category: "Sales & Marketing",
    level: "Beginner",
  },
];
