#!/usr/bin/env node
/**
 * sync-skills.js
 *
 * Reads all SKILL.md files from .agents/skills/tech/ and .agents/skills/domain/
 * and propagates them to the config directories of supported AI tools:
 *
 *   Claude Code   → .claude/commands/<name>.md
 *   GitHub Copilot → .github/copilot-instructions.md  (marker-based injection)
 *   Cursor         → .cursor/rules/<name>.mdc
 *   Gemini CLI     → .gemini/skills/<name>/SKILL.md
 *
 * Usage:
 *   node scripts/sync-skills.js
 *
 * The script is idempotent — safe to run multiple times.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

// ─── Paths ────────────────────────────────────────────────────────────────────

const SKILLS_ROOT = path.join(ROOT, '.agents', 'skills');
const TECH_DIR = path.join(SKILLS_ROOT, 'tech');
const DOMAIN_DIR = path.join(SKILLS_ROOT, 'domain');

const TARGETS = {
  claude: path.join(ROOT, '.claude', 'commands'),
  copilot: path.join(ROOT, '.github', 'copilot-instructions.md'),
  cursor: path.join(ROOT, '.cursor', 'rules'),
  gemini: path.join(ROOT, '.gemini', 'skills'),
};

const MARKER_START = '<!-- SKILLS:START — auto-generated by scripts/sync-skills.js, do not edit manually -->';
const MARKER_END = '<!-- SKILLS:END -->';

// ─── Helpers ──────────────────────────────────────────────────────────────────

function ensureDir(dirPath) {
  if (!fs.existsSync(dirPath)) {
    fs.mkdirSync(dirPath, { recursive: true });
    console.log(`  [mkdir] ${path.relative(ROOT, dirPath)}`);
  }
}

/**
 * Parse YAML front matter from a SKILL.md string.
 * Returns { name, description } — both strings, possibly empty.
 */
function parseFrontMatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return { name: '', description: '' };
  const block = match[1] ?? '';
  const nameMatch = block.match(/^name:\s*(.+)$/m);
  const descMatch = block.match(/^description:\s*([\s\S]*?)(?=\n\w|$)/m);
  return {
    name: nameMatch?.[1]?.trim() ?? '',
    description: descMatch?.[1]?.trim().replace(/\n\s+/g, ' ') ?? '',
  };
}

/**
 * Collect all SKILL.md files from a category directory.
 * Returns an array of { skillDir, name, content, frontMatter }.
 */
function collectSkills(categoryDir, category) {
  if (!fs.existsSync(categoryDir)) {
    console.warn(`  [warn] directory not found: ${path.relative(ROOT, categoryDir)}`);
    return [];
  }
  const skills = [];
  for (const entry of fs.readdirSync(categoryDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const skillFile = path.join(categoryDir, entry.name, 'SKILL.md');
    if (!fs.existsSync(skillFile)) {
      console.warn(`  [warn] missing SKILL.md in ${entry.name}`);
      continue;
    }
    const content = fs.readFileSync(skillFile, 'utf8');
    const frontMatter = parseFrontMatter(content);
    skills.push({
      skillDir: path.join(categoryDir, entry.name),
      dirName: entry.name,
      category,
      content,
      frontMatter,
    });
  }
  return skills.sort((a, b) => a.dirName.localeCompare(b.dirName));
}

// ─── Target: Claude Code (.claude/commands/) ──────────────────────────────────

function syncClaude(skills) {
  ensureDir(TARGETS.claude);
  let count = 0;
  for (const skill of skills) {
    const dest = path.join(TARGETS.claude, `${skill.dirName}.md`);
    fs.writeFileSync(dest, skill.content, 'utf8');
    count++;
  }
  console.log(`  [claude] wrote ${count} command files → .claude/commands/`);
}

// ─── Target: GitHub Copilot (.github/copilot-instructions.md) ─────────────────

function syncCopilot(skills) {
  if (!fs.existsSync(TARGETS.copilot)) {
    console.warn(`  [warn] ${path.relative(ROOT, TARGETS.copilot)} not found — skipping Copilot sync`);
    return;
  }

  // Build the injected block
  const techSkills = skills.filter(s => s.category === 'tech');
  const domainSkills = skills.filter(s => s.category === 'domain');

  const lines = [];
  lines.push('');
  lines.push('## Tech Skills');
  lines.push('');
  for (const s of techSkills) {
    lines.push(`### ${s.frontMatter.name || s.dirName}`);
    lines.push('');
    lines.push(s.frontMatter.description || '');
    lines.push('');
    lines.push(`_Source: \`.agents/skills/tech/${s.dirName}/SKILL.md\`_`);
    lines.push('');
  }

  lines.push('## Domain Skills');
  lines.push('');
  for (const s of domainSkills) {
    lines.push(`### ${s.frontMatter.name || s.dirName}`);
    lines.push('');
    lines.push(s.frontMatter.description || '');
    lines.push('');
    lines.push(`_Source: \`.agents/skills/domain/${s.dirName}/SKILL.md\`_`);
    lines.push('');
  }

  const injected = lines.join('\n');

  let original = fs.readFileSync(TARGETS.copilot, 'utf8');

  if (original.includes(MARKER_START) && original.includes(MARKER_END)) {
    // Replace existing block
    const startIdx = original.indexOf(MARKER_START);
    const endIdx = original.indexOf(MARKER_END) + MARKER_END.length;
    original = original.slice(0, startIdx) + MARKER_START + injected + MARKER_END + original.slice(endIdx);
  } else {
    // Append block at end
    original = original.trimEnd() + '\n\n---\n\n## Project Skills\n\n' + MARKER_START + injected + MARKER_END + '\n';
  }

  fs.writeFileSync(TARGETS.copilot, original, 'utf8');
  console.log(`  [copilot] updated ${path.relative(ROOT, TARGETS.copilot)}`);
}

// ─── Target: Cursor (.cursor/rules/) ─────────────────────────────────────────

function syncCursor(skills) {
  ensureDir(TARGETS.cursor);
  let count = 0;
  for (const skill of skills) {
    const { name, description } = skill.frontMatter;
    // Cursor .mdc format: frontmatter with description, then the skill body
    const body = skill.content.replace(/^---[\s\S]*?---\n/, ''); // strip SKILL.md frontmatter
    const cursorContent = `---\ndescription: ${description || name}\n---\n\n${body}`;
    const dest = path.join(TARGETS.cursor, `${skill.dirName}.mdc`);
    fs.writeFileSync(dest, cursorContent, 'utf8');
    count++;
  }
  console.log(`  [cursor] wrote ${count} rule files → .cursor/rules/`);
}

// ─── Target: Gemini CLI (.gemini/skills/) ─────────────────────────────────────

function syncGemini(skills) {
  ensureDir(TARGETS.gemini);
  let count = 0;
  for (const skill of skills) {
    const destDir = path.join(TARGETS.gemini, skill.dirName);
    ensureDir(destDir);
    fs.writeFileSync(path.join(destDir, 'SKILL.md'), skill.content, 'utf8');
    count++;
  }
  console.log(`  [gemini] wrote ${count} skill files → .gemini/skills/`);
}

// ─── Main ─────────────────────────────────────────────────────────────────────

function main() {
  console.log('sync-skills: reading from .agents/skills/\n');

  const techSkills = collectSkills(TECH_DIR, 'tech');
  const domainSkills = collectSkills(DOMAIN_DIR, 'domain');
  const allSkills = [...techSkills, ...domainSkills];

  if (allSkills.length === 0) {
    console.error('error: no SKILL.md files found — aborting');
    process.exit(1);
  }

  console.log(`  found ${techSkills.length} tech skill(s) and ${domainSkills.length} domain skill(s)\n`);

  console.log('syncing targets:');
  syncClaude(allSkills);
  syncCopilot(allSkills);
  syncCursor(allSkills);
  syncGemini(allSkills);

  console.log(`\ndone — ${allSkills.length} skill(s) propagated to 4 targets.`);
}

main();
