import dotenv from 'dotenv';

dotenv.config();

const env = process.env;

export const envConfig = {
    ENVIRONMENT: env.ENVIRONMENT,
    DOMAIN_URL: env.DOMAIN_URL,
    KONG_URL: env.KONG_URL,
    SUNBIRD_ANONYMOUS_SESSION_SECRET: env.SUNBIRD_ANONYMOUS_SESSION_SECRET,
    SUNBIRD_YUGABYTE_HOST: env.SUNBIRD_YUGABYTE_HOST,
    KONG_ANONYMOUS_FALLBACK_TOKEN: env.KONG_ANONYMOUS_FALLBACK_TOKEN,
    KONG_ANONYMOUS_DEVICE_REGISTER_TOKEN: env.KONG_ANONYMOUS_DEVICE_REGISTER_TOKEN,
    SUNBIRD_LOGGEDIN_SESSION_SECRET: env.SUNBIRD_LOGGEDIN_SESSION_SECRET,
    KONG_LOGGEDIN_FALLBACK_TOKEN: env.KONG_LOGGEDIN_FALLBACK_TOKEN,
    KONG_LOGGEDIN_DEVICE_REGISTER_TOKEN: env.KONG_LOGGEDIN_DEVICE_REGISTER_TOKEN,
    PORTAL_REALM: env.PORTAL_REALM,
    KEYCLOAK_BASE_SERVER_URL: env.KEYCLOAK_BASE_SERVER_URL,
    PORTAL_AUTH_SERVER_CLIENT: env.PORTAL_AUTH_SERVER_CLIENT,

    // OPTIONAL ENVIRONMENT VARIABLES
    PORT: parseInt(env.PORT || '3000'),
    SUNBIRD_PORTAL_LOG_LEVEL: env.SUNBIRD_PORTAL_LOG_LEVEL || 'debug',
    SUNBIRD_ANONYMOUS_SESSION_TTL: parseInt(env.SUNBIRD_ANONYMOUS_SESSION_TTL || "60000"),
    SUNBIRD_YUGABYTE_PORT: parseInt(env.SUNBIRD_YUGABYTE_PORT || '5433'),
    SUNBIRD_YUGABYTE_DATABASE: env.SUNBIRD_YUGABYTE_DATABASE || 'portal',
    SUNBIRD_YUGABYTE_USER: env.SUNBIRD_YUGABYTE_USER,
    SUNBIRD_YUGABYTE_PASSWORD: env.SUNBIRD_YUGABYTE_PASSWORD,
    SUNBIRD_PORTAL_SESSION_STORE: env.SUNBIRD_PORTAL_SESSION_STORE || 'in-memory',
    GOOGLE_RECAPTCHA_VERIFY_URL: env.GOOGLE_RECAPTCHA_VERIFY_URL || 'https://www.google.com/recaptcha/api/siteverify',
    GOOGLE_RECAPTCHA_SECRET: env.GOOGLE_RECAPTCHA_SECRET || '',
    APPID: (env.ENVIRONMENT || 'local') + '.' + (env.SUNBIRD_PORTAL_INSTANCE || 'sunbird') + '.portal',
    LEARN_BASE_URL: env.LEARN_BASE_URL || 'http://userorg-service:9000',
};
