import dotenv from 'dotenv';

const env = process.env;

dotenv.config();

export const envConfig = {
    ENVIRONMENT: env.ENVIRONMENT || 'local',
    SUNBIRD_ANONYMOUS_SESSION_SECRET: env.SUNBIRD_ANONYMOUS_SESSION_SECRET || 'sunbird_anonymous_session_secret',
    SUNBIRD_YUGABYTE_HOST: env.SUNBIRD_YUGABYTE_HOST || 'localhost',
    KONG_ANONYMOUS_FALLBACK_TOKEN: env.KONG_ANONYMOUS_FALLBACK_TOKEN || '',
    KONG_ANONYMOUS_DEVICE_REGISTER_TOKEN: env.KONG_ANONYMOUS_DEVICE_REGISTER_TOKEN || '',
    KONG_ANONYMOUS_DEVICE_REGISTER_API: env.KONG_ANONYMOUS_DEVICE_REGISTER_API || '',

    // OPTIONAL ENVIRONMENT VARIABLES
    PORT: parseInt(env.PORT || '3000'),
    SUNBIRD_PORTAL_LOG_LEVEL: env.SUNBIRD_PORTAL_LOG_LEVEL || 'debug',
    SUNBIRD_ANONYMOUS_SESSION_TTL: parseInt(env.SUNBIRD_ANONYMOUS_SESSION_TTL || "60000"),
    SUNBIRD_YUGABYTE_PORT: parseInt(env.SUNBIRD_YUGABYTE_PORT || '5433'),
    SUNBIRD_YUGABYTE_DATABASE: env.SUNBIRD_YUGABYTE_DATABASE || 'portal',
    SUNBIRD_YUGABYTE_USER: env.SUNBIRD_YUGABYTE_USER || 'yugabyte',
    SUNBIRD_YUGABYTE_PASSWORD: env.SUNBIRD_YUGABYTE_PASSWORD || 'yugabyte',
    SUNBIRD_YUGABYTE_CQL_PORT: parseInt(env.SUNBIRD_YUGABYTE_CQL_PORT || '9042'),
    SUNBIRD_YUGABYTE_KEYSPACE: env.SUNBIRD_YUGABYTE_KEYSPACE || 'form_service',
    SUNBIRD_YUGABYTE_CQL_USER: env.SUNBIRD_YUGABYTE_CQL_USER || 'yugabyte',
    SUNBIRD_YUGABYTE_CQL_PASSWORD: env.SUNBIRD_YUGABYTE_CQL_PASSWORD || 'yugabyte',
    SUNBIRD_PORTAL_SESSION_STORE: env.SUNBIRD_PORTAL_SESSION_STORE || 'in-memory',

    GOOGLE_RECAPTCHA_VERIFY_URL: env.GOOGLE_RECAPTCHA_VERIFY_URL || 'https://www.google.com/recaptcha/api/siteverify',
    GOOGLE_RECAPTCHA_SECRET: env.GOOGLE_RECAPTCHA_SECRET || ''
};
